#!/bin/bash

#ddev-generated
## Description: Run platform.sh CLI inside the web container
## Usage: platform [flags] [args]
## Example: "platform user:list" or "platform ssh" or "platform service:list"
## ExecRaw: true

platform "$@"
